### ISSUE TITLE
请问会支持vue3吗

### ISSUE THREAD

**Issue by LnksW** [lovewmf/uni-code#1]

**Comment by lovewmf** [comment]
> _未提供说明。_

本地已经兼容了vue3 只是还没发布

**Comment by LnksW** [comment]
@lovewmf 最近有发布的计划吗

**Comment by lovewmf** [comment]
> @lovewmf 最近有发布的计划吗
估计到年后了 如果比较急可以单独使用js_sdk

**Comment by LnksW** [comment]
> > @lovewmf 最近有发布的计划吗
> > 估计到年后了 如果比较急可以单独使用js_sdk

确实有些急，请问如何使用jjs_sdk

**Comment by lovewmf** [comment]
> > > @lovewmf 最近有发布的计划吗
> > > 估计到年后了 如果比较急可以单独使用js_sdk
> 
> 确实有些急，请问如何使用jjs_sdk

参考示例https://img.lovewmf.com/CODE-VUE3.zip

**Comment by LnksW** [comment]
> 

好的，很感谢

**Comment by LnksW** [comment]
> > > > @lovewmf 最近有发布的计划吗
> > > > 估计到年后了 如果比较急可以单独使用js_sdk
> > 
> > 
> > 确实有些急，请问如何使用jjs_sdk
> 
> 参考示例https://img.lovewmf.com/CODE-VUE3.zip

小程序真机调试遇到层级过高的问题，有没有什么解决办法，cover-view尝试过，没效果

**Comment by tanghongrui** [comment]
> > > > @lovewmf
> > > > 如果比较急可以单独使用 js_sdk有发布的计划吗？
> > 
> > 
> > 确实有些急，请问如何使用jjs_sdk
> 
> 参考示例https://img.lovewmf.com/CODE-VUE3.zip

示例非常好用，感谢感谢

**Comment by LnksW** [comment]
> > > > > @lovewmf 最近有发布的计划吗
> > > > > 估计到年后了 如果比较急可以单独使用js_sdk
> > > 
> > > 
> > > 确实有些急，请问如何使用jjs_sdk
> > 
> > 
> > 参考示例https://img.lovewmf.com/CODE-VUE3.zip
> 
> 小程序真机调试遇到层级过高的问题，有没有什么解决办法，cover-view尝试过，没效果

问题已解决

**Comment by tanghongrui** [comment]
> 
朋友，有没有遇到码显示不全的问题，我在预览调试的时候，不断刷新，偶尔会出现码缺失一部分

**Comment by LnksW** [comment]
> > 
> 
> 朋友，有没有遇到码显示不全的问题，我在预览调试的时候，不断刷新，偶尔会出现码缺失一部分

没有，但是好像只能生成code32的码

**Comment by tanghongrui** [comment]
> > > > @lovewmf
> > > > 如果比较急可以单独使用 js_sdk有发布的计划吗？
> > 
> > 
> > 确实有些急，请问如何使用jjs_sdk
> 
> 参考示例https://img.lovewmf.com/CODE-VUE3.zip
请问有没有遇到码显示不全的问题，我在预览调试的时候，不断刷新，偶尔会出现码缺失一部分
