### ISSUE TITLE
能不能支持自动导入, 每次新项目都要取写easycom规则

### ISSUE THREAD

**Issue by pylist** [lovewmf/uni-code#10]

**Comment by lovewmf** [comment]
具体是什么样的自动导入

**Comment by pylist** [comment]
![image](https://user-images.githubusercontent.com/52667561/203257617-1b0f5b64-45db-493d-ba48-7f894326c466.png)
就是省掉这个easycom

**Comment by lovewmf** [comment]
可以不用这个 跟正常引入组件一样
