### ISSUE TITLE
开发者，你好，二维码有些生成的扫不出来。

### ISSUE THREAD

**Issue by yoonaiorlim** [lovewmf/uni-code#3]
开发者，你好，二维码有些生成的扫不出来。比如：18693530，这个生成的二维码就扫不出来，希望你能修复一下。谢谢
![image](https://user-images.githubusercontent.com/78140083/159829090-395d8a73-bbb7-41f4-8459-a4235c3542da.png)

**Comment by lovewmf** [comment]
无法识别 请修改参数level的值 1～4  后面会修改生成方式

**Comment by lovewmf** [comment]
已经修复了
