### ISSUE TITLE
安卓手机保存图片时黑底问题

### ISSUE THREAD

**Issue by excxapp** [lovewmf/uni-code#7]
安卓手机保存图片时图片保存下来是黑底

**Comment by excxapp** [comment]
条形码带文字时，文字底为黑底，是安卓手机，默认格式也是jpg

**Comment by excxapp** [comment]
初步判断时：带文字时，文字尺寸超过初始化设置图片尺寸，安卓微信的bug造成，
优化生成图片的尺寸不要绑定条形码尺寸

**Comment by lovewmf** [comment]
> 条形码带文字时，文字底为黑底，是安卓手机，默认格式也是jpg

具体截图我看

**Comment by excxapp** [comment]
![image](https://user-images.githubusercontent.com/4355581/178127467-3ccac571-9c60-48fa-9e82-355bf2d07e9c.png)

**Comment by lovewmf** [comment]
我没有android手机 只能在模拟器上测 测试正常你更新一下版本试试 以前条形码图片保存不全

**Comment by lovewmf** [comment]
> 我没有android手机 只能在模拟器上测 测试正常你更新一下版本试试 以前条形码图片保存不全






> ![image](https://user-images.githubusercontent.com/4355581/178127467-3ccac571-9c60-48fa-9e82-355bf2d07e9c.png)
> 我没有android手机 只能在模拟器上测 测试正常你更新一下版本试试 以前条形码图片保存不全

**Comment by lovewmf** [comment]
> ![image](https://user-images.githubusercontent.com/4355581/178127467-3ccac571-9c60-48fa-9e82-355bf2d07e9c.png)

> 我没有android手机 只能在模拟器上测 测试正常你更新一下版本试试 以前条形码图片保存不全
